// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WizardingBricks.Models;

#nullable disable

namespace WizardingBricks.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251115044916_AddImagePreviewAndPartsNumberToMinifigureModel")]
    partial class AddImagePreviewAndPartsNumberToMinifigureModel
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CategorySet", b =>
                {
                    b.Property<int>("CategoriesId")
                        .HasColumnType("int");

                    b.Property<int>("SetsId")
                        .HasColumnType("int");

                    b.HasKey("CategoriesId", "SetsId");

                    b.HasIndex("SetsId");

                    b.ToTable("CategorySet");
                });

            modelBuilder.Entity("MinifigureSet", b =>
                {
                    b.Property<int>("MinifiguresId")
                        .HasColumnType("int");

                    b.Property<int>("SetsId")
                        .HasColumnType("int");

                    b.HasKey("MinifiguresId", "SetsId");

                    b.HasIndex("SetsId");

                    b.ToTable("MinifigureSet");
                });

            modelBuilder.Entity("WizardingBricks.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CharacterId")
                        .HasColumnType("int");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CharacterId");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("WizardingBricks.Models.Character", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Characters");
                });

            modelBuilder.Entity("WizardingBricks.Models.Minifigure", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CharacterId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Number_Of_Parts")
                        .HasColumnType("int");

                    b.Property<string>("Preview_Image_URL")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CharacterId");

                    b.ToTable("Minifigures");
                });

            modelBuilder.Entity("WizardingBricks.Models.Set", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Instructions_URL")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Number_Of_Parts")
                        .HasColumnType("int");

                    b.Property<string>("Preview_Image_URL")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Set_Number")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Sets");
                });

            modelBuilder.Entity("CategorySet", b =>
                {
                    b.HasOne("WizardingBricks.Models.Category", null)
                        .WithMany()
                        .HasForeignKey("CategoriesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WizardingBricks.Models.Set", null)
                        .WithMany()
                        .HasForeignKey("SetsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MinifigureSet", b =>
                {
                    b.HasOne("WizardingBricks.Models.Minifigure", null)
                        .WithMany()
                        .HasForeignKey("MinifiguresId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WizardingBricks.Models.Set", null)
                        .WithMany()
                        .HasForeignKey("SetsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("WizardingBricks.Models.Category", b =>
                {
                    b.HasOne("WizardingBricks.Models.Character", null)
                        .WithMany("Categories")
                        .HasForeignKey("CharacterId");
                });

            modelBuilder.Entity("WizardingBricks.Models.Minifigure", b =>
                {
                    b.HasOne("WizardingBricks.Models.Character", "Character")
                        .WithMany("Minifigures")
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Character");
                });

            modelBuilder.Entity("WizardingBricks.Models.Character", b =>
                {
                    b.Navigation("Categories");

                    b.Navigation("Minifigures");
                });
#pragma warning restore 612, 618
        }
    }
}
